#python train.py --data isic2018 --model dff MODEL.NAME DFF_T TRAIN.EPOCHS 20
python train.py --data isic2018 --model dff MODEL.NAME DFF_T TRAIN.EPOCHS 40 TRAIN.BATCH_SIZE 128 NOTE BASELINE
python train.py --data isic2018 --model dff MODEL.NAME DFF_S TRAIN.EPOCHS 40 TRAIN.BATCH_SIZE 128 NOTE BASELINE
python train.py --data isic2018 --model dff MODEL.NAME DFF_B TRAIN.EPOCHS 40 TRAIN.BATCH_SIZE 64 NOTE BASELINE



python train.py --data isic2018 --model dff MODEL.NAME DFF_S TRAIN.EPOCHS 40 TRAIN.BATCH_SIZE 64 TRAIN.STRATEGY warmup NOTE OURS
python train.py --data isic2018 --model dff MODEL.NAME DFF_S TRAIN.EPOCHS 40 TRAIN.BATCH_SIZE 64 TRAIN.STRATEGY linear NOTE OURS
python train.py --data isic2018 --model dff MODEL.NAME DFF_S TRAIN.EPOCHS 40 TRAIN.BATCH_SIZE 64 TRAIN.STRATEGY cos NOTE OURS
python train.py --data isic2018 --model dff MODEL.NAME DFF_S TRAIN.EPOCHS 40 TRAIN.BATCH_SIZE 64 TRAIN.STRATEGY consist-1.0 NOTE OURS
python train.py --data isic2018 --model dff MODEL.NAME DFF_S TRAIN.EPOCHS 40 TRAIN.BATCH_SIZE 64 TRAIN.STRATEGY consist-0.8 NOTE OURS
python train.py --data isic2018 --model dff MODEL.NAME DFF_S TRAIN.EPOCHS 40 TRAIN.BATCH_SIZE 64 TRAIN.STRATEGY consist-0.5 NOTE OURS
python train.py --data isic2018 --model dff MODEL.NAME DFF_S TRAIN.EPOCHS 40 TRAIN.BATCH_SIZE 64 TRAIN.STRATEGY consist-0.1 NOTE OURS

